### ISSUE TITLE
Progress in URL bar broken...

### ISSUE THREAD

**Issue by hightechdude** [SparkyBluefang/S4E#34]
The "Show progress in the location bar" feature is suddenly misbehaving.  Instead of the bar displaying in the selected Top, Bottom, or Fill position, it will only display a narrow progress line thru the center of the location bar while nudging the url address to the right.  It seems to have occurred after the latest FF update.
FF 44.0.2, OSX 10.10.5

**Comment by SparkyBluefang** [comment]
That generally happens because you have a conflicting extension installed. Upgrading Firefox can cause extension to load in a different order, which may explain why it suddenly appeared with a Firefox update.

You can try enabling:

S4E Preferences -> Advanced -> [X] Attempt to force the Location Bar XBL binding.

**Comment by hightechdude** [comment]
Thanks for the heads-up... it was a conflict with a recently updated Adobe Acrobat extension.  I dumped that and S4E works fine now.  Thanks again.
