### ISSUE TITLE
Status4Ever gets blocked and disabled by Pale Moon Browser

### ISSUE THREAD

**Issue by satovey** [SparkyBluefang/S4E#49]
With the upcoming Firefox kill all addons change, I have decided to switch to Pale Moon a Firefox clone, so that I can continue to use the addons that I want to use.. But even this browser has issues with some addons.

Status-4-ever is  blocked and disabled by the browser. 
Here is the message that is given on the more information page.

This Add-on to your browser has been blocked.
Your add-on has been blocked or disabled because it is known to be malware, has known security vulnerabilities (especially in the case of plugins), is known to cause instability, or known to cause (severe) usability issues. In the latter 2 cases, when the blocked add-on is an extension, you may be able to find an alternative on our add-ons site https://addons.palemoon.org/.

More detailed information about why it has been blocked may be available on the Mozilla website. https://blocklist.addons.mozilla.org/en-US/firefox/blocked/pm102

I appreciate this plugin as it maintains the security that one receives when being able verify the link location while hovering over the link. 

The biggest problem I have with these browser warnings is that they take away the users choice to use the extension despite the warning.

**Comment by SparkyBluefang** [comment]
This is intentional behavior by the Pale Moon developer. PM contains a customized fork of S4E that would cause conflicts if both versions were installed.

As it stands, S4S is not compatible with PM. Mozilla dropped support for the legacy download API in Firefox 26, and the legacy UI in Firefox 29. S4E dropped support for both in version 2014.11.12.23a when Mozilla discontinued Firefox ESR 24.
