### ISSUE TITLE
Not working in FF55 

### ISSUE THREAD

**Issue by albertalbs** [SparkyBluefang/S4E#53]
Till date I was using S4E with "Classic Theme Restorer".  

After upgrading to FF 55, S4E is not working anymore...

Updates are coming?

**Comment by jep-dev** [comment]
A lot of my extensions are broken - I think this has to do with the Electrolysis/WebExtensions transition, even though the official switch is in November. I hope someone more knowledgeable can comment.

<sup><strong>FF 54.02 64-bit Linux</strong></sup>

**Comment by Krzysiu** [comment]
If that helps, it doesn't work for me either (Fx 55.0.2 Win64), but it was OK until now, i.e. it worked well after update and now "randomly" doesn't work anymore.

**Comment by jep-dev** [comment]
I removed S4E and I'm getting 'native' HREF rollover text in the SW corner of the content frame. I installed it again and it still just says "Status Text", but the rollover text is missing.

FWIW, I just found a Web Extension port of Stylish called 'Stylus' (and also got verification that userChrome.css will enable UI styles) so a pure CSS implementation is possible. If it's just me, I'll get by without, but I bring it up because S4E appears to be consuming the rollover event with JS, despite not displaying the results.

**Comment by albertalbs** [comment]
@Krzysiu Yes. CTR is still working for me.

**Comment by albertalbs** [comment]
@jep-dev Found a fixed version of S4E. 

**Download this and install: (Working Version)**

- https://goo.gl/rhUZGM (Direct Download)

- https://goo.gl/cyWMxi (Other version to try)

**Comment by Krzysiu** [comment]
Thanks, @albertalbs for answer and the link. I confirm it works with 55.0.2 and 55.0.3 with Firefox 64 for Windows. For historical reasons: right now the current version of S4E is 2017.03.19.12b and I used that one.

**Comment by SparkyBluefang** [comment]
Version 2017.08.20.15 has been released.
