### ISSUE TITLE
Compatibility with Firefox 57+

### ISSUE THREAD

**Issue by Freudentaumel** [SparkyBluefang/S4E#54]
Hi there,

I´d like to ask you if there will be an update for Firefox 57+?

Thank you very much
Gerhard

**Comment by albertalbs** [comment]
Try this: https://github.com/SparkyBluefang/S4E/issues/53#issuecomment-323811143

**Comment by Freudentaumel** [comment]
Unfortunately, I can not see from # 53, whether S4E will be adapted to Firefox 57+. Maybe it is only because of my inadequate English.

Would the answer to my question be possible in other words?

Thank you very much
Gerhard

**Comment by albertalbs** [comment]
@Freudentaumel 

This version https://goo.gl/Z9M5iH may work in 57+ also. But not sure.

**Comment by davidhedlund** [comment]
I'm looking forward to use Status-4-Evar as a WebExtension.

**Comment by SparkyBluefang** [comment]
The WebExtension API doesn't provide any method to create a toolbar or provide UI elements aside from an iconic button[1]. There also does not appear to be any API to get statuses, tab/browser progress, .

So, as it currently stands, there will be no WebExtension version. It will continue to function on nightly developer builds as long as legacy extension and XBL support has not been removed completely.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1215064
`Toolbars are on the WebExtensions roadmap. The need for additional details around policy, implementation and UX will, unfortunately, prevent them from appearing in 57.`

**Comment by davidhedlund** [comment]
@SparkyBluefang Thank you for informing us.

**Comment by Anke** [comment]
So hopefully they'll get around to that ... 
What good is a Developer Edition that constantly stops your work flow because much needed addons are missing? It seems web developers are somehow serving as guinea pigs for Mozilla developers ...

**Comment by zeroxxx2** [comment]
Found this thread thru Google.

Sad, but I guess it can't be helped -- hopefully Mozilla implements the required stuffs sooner than later.

**Comment by hakai** [comment]
Ok. That's it. I'm switching to Firefox 52 ESR. 

Unbelievable how they stop support for the old addon type before Web Extensions has all needed functionality.

**Comment by resolritter** [comment]
@hakai No need to go back in time that far. You can still download Firefox 56 from https://ftp.mozilla.org/pub/firefox/releases/ and use it just fine.

S4E was still available on FF56 if you had enabled legacy extensions usage. I was using it until yesterday with no issues (even the custom settings worked perfectly fine), but I guess Quantum really took it away for good. ☹️

**Comment by SparkyBluefang** [comment]
@jpsouzasilva I would be remiss in not pointing out that running an unsupported browser version is highly inadvisable. Firefox 56 is end-of-life and won't receive any more security updates. However, Firefox 52 ESR will be supported until mid next year.

Hopefully, by then, the Web Extension API will be a bit more usable.

**Comment by hoodsmom** [comment]
Interestingly, even though S4E (and at least one other favorite extension) was supposed to have been deactivated by FF57, in my setup, it briefly wasn't. Unfortunately when I logged in after a few more times all the legacy extensions really had been deactivated.

Just FYI, in case you ever are able to develop it for FF57, there's some sort of extension conflict with S4E and the official download button (the one that's supposed to open the download window - equivalent of command-J). With S4E enabled, that button "doesn't do anything." I'll live with it so that I can have S4E.

**Comment by SylwesterZarebski** [comment]
Time passed, but Mozilla did little to nothing to resolve this problem.
Also Firefox 52 ESR soon will be unsupported the same as 56 or any other version with legacy addon support.

**Comment by xlovinglyx** [comment]
Please update to ff68, one status bar, aka addon-bar, i'm not asking hell ((

**Comment by SylwesterZarebski** [comment]
[**@xlovinglyx**](https://github.com/xlovinglyx) Until Mozilla fixes their product, use alternatives like Waterfox, which support legacy extensions.

**Comment by crudebuster** [comment]
Yesterday I had my netbook working and it synced a theme update (Firefox Robot by nobox) from the firefox I had there to my Waterfox in my desktop. I was furious, because obviously the new footer was blank, leaving my Status-4-Evar bar horribly bleached and other themes negate the options to change it clearly, leaving the option to dark or other bland themes.

I had to install Personas Plus 1.8.3 (and disable updates) from the Classic Addons Archive so it had the options to put a header and footer pictures as well as the font color, luckily i had them stashed around, as I use them in Libreoffice too. 

The newer Personas Plus is just a goodbye message trying to convince people to change to something called Firefox Colors... I hope the Waterfox guy keeps maintaining this last stand against the uncustomization of Mozilla... 

![footer](https://user-images.githubusercontent.com/7358179/61963448-f9f9bd80-afa1-11e9-8742-1f340785555e.jpg)
